services:
  - type: web
    name: sushibread-mev-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node scripts/telegram_daemon.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.10.0
      - key: BASE_CHAIN_ID
        value: "8453"
      - key: BASE_RPC_URL
        value: https://developer-access-mainnet.base.org
      - key: BASE_BOT_WALLET_ADDRESS
        sync: false
      - key: BASE_BOT_PRIVATE_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PROFIT_RECIPIENT_WALLET_ADDRESS
        sync: false
