services:
  - type: worker
    name: sushibread-mev-sniper
    runtime: node
    buildCommand: npm install
    startCommand: node scripts/telegram_daemon.js
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
      - key: BASE_CHAIN_ID
        value: "8453"
      - key: BASE_RPC_URL
        value: https://developer-access-mainnet.base.org
      - key: BASE_BOT_WALLET_ADDRESS
        value: 0x3fE94347b0FDE33947c7b43d80618BA4b99dB647
      - key: BASE_BOT_PRIVATE_KEY
        value: 0xc1ecffae315aaeafa23474aac85eb45fb635b01a8daf78da526edaec12235e19
      - key: TELEGRAM_BOT_TOKEN
        value: 8260297618:AAFSHAq-Ukpj-3-GbIBQBHU_4FHCmKCUdZo
      - key: PROFIT_RECIPIENT_WALLET_ADDRESS
        value: 0xe00681dfeE4644F46c67Ff3283849EFf0Ae06aC8
